services:
  postgres:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    volumes:
      - streamzen-postgres:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  streamzen-postgres:
