name: Checkov scan on PR

on:
  pull_request:
    paths:
      - "infra/**"

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  checkov:
    name: Checkov scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkov
        id: checkov_step
        uses: bridgecrewio/checkov-action@v12
        continue-on-error: true
        with:
          directory: ${{ github.workspace }}
          framework: terraform
          soft_fail: false
          # CKV_AWS_173: Check encryption settings for Lambda environmental variable
          # CKV_AWS_174: AWS CloudFront web distribution using insecure TLS version
          # CKV_AWS_305: Does not have a default root object configured
          # CKV_AWS_310: CloudFront distributions do not have origin failover configured
          # CKV_AWS_18: AWS Access logging not enabled on S3 buckets
          # CKV_AWS_21: Ensure all data stored in the S3 bucket have versioning enabled
          # CKV_AWS_115: AWS Lambda function is not configured for function-level concurrent execution Limit
          # CKV_AWS_116: AWS Lambda function is not configured for a DLQ
          # CKV_AWS_50: X-Ray tracing is enabled for Lambda
          # CKV_AWS_117: Ensure that AWS Lambda function is configured inside a VPC
          # CKV_AWS_158: Ensure that CloudWatch Log Group is encrypted by KMS
          # CKV2_AWS_61: Ensure that an S3 bucket has a lifecycle configuration
          # CKV2_AWS_62: Ensure S3 buckets should have event notifications enabled
          # CKV_AWS_144: Ensure that S3 bucket has cross-region replication enabled
          # CKV_AWS_337: Ensure SSM parameters are using KMS CMK
          # CKV_AWS_109: Ensure IAM policies does not allow permissions management / resource exposure without constraints
          # CKV_AWS_111: Ensure IAM policies does not allow write access without constraints
          # CKV_AWS_356: Ensure no IAM policies documents allow “*” as a statement’s resource for restrictable actions
          skip_check: CKV_AWS_173,CKV_AWS_174,CKV_AWS_305,CKV_AWS_310,CKV_AWS_18,CKV_AWS_21,CKV_AWS_115,CKV_AWS_116,CKV_AWS_50,CKV_AWS_117,CKV_AWS_158,CKV2_AWS_61,CKV2_AWS_62,CKV_AWS_144,CKV_AWS_337,CKV_AWS_109,CKV_AWS_111,CKV_AWS_356

      - name: Find Comment
        if: steps.checkov_step.outcome == 'failure'
        uses: peter-evans/find-comment@v3
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: Checkov found

      - name: Create or update comment
        if: steps.checkov_step.outcome == 'failure'
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### Checkov found issues in the code.
            Please review "Checkov scan".
          edit-mode: replace
