name: Deploy static client to S3

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
env:
  BUCKET_NAME: streamzen-static-frontend-dev-bucket

jobs:
  build:
    name: Build bundle
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: |
          corepack enable
          yarn install

      - name: Build
        run: yarn build

      - name: Save bundle
        uses: actions/upload-artifact@v4
        with:
          name: bundle
          path: ./dist/

  deploy:
    name: Deploy to S3
    runs-on: ubuntu-latest
    needs: build
    environment: production
    steps:
      - name: Download bundle
        uses: actions/download-artifact@v4
        with:
          name: bundle
          path: /tmp/bundle/dist/

      - name: Setup AWS
        uses: ./.github/actions/setup-aws

      - name: Deploy
        run: aws s3 sync --delete /tmp/bundle/dist s3://${{ env.BUCKET_NAME }}
