name: Deploy server app to ECR

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  deploy:
    name: Deploy to ECR
    runs-on: ubuntu-latest
    needs: build
    environment: production
    steps:
      - run: echo "Hello, world!"
