name: Pluralith

on:
  workflow_dispatch:
#   pull_request:
#     branches:
#       - main

env:
  PLURALITH_ORG_ID: 864448565
  PLURALITH_PROJECT_ID: streamzen-monorepo
  PLURALITH_PROJECT_NAME: streamzen-monorepo

jobs:
  pluralith:
    runs-on: ubuntu-latest
    env:
      working-directory: infra

    name: Run Pluralith
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup AWS
        uses: ./.github/actions/setup-aws

      - name: TF tools
        uses: ./.github/actions/setup-tf-tools

      - name: Terraform Init
        run: terragrunt init

      - name: Pluralith Init
        uses: Pluralith/actions/init@v1.4.0
        with:
          terraform-path: "${{ env.working-directory }}"
          api-key: ${{ secrets.PLURALITH_API_KEY }}

      - name: Pluralith Run
        uses: Pluralith/actions/run@v1.4.0
        with:
          terraform-command: "plan"
          terraform-path: "${{ env.working-directory }}"
          show-changes: true
          show-drift: true

      - name: Pluralith Comment
        uses: Pluralith/actions/comment@v1.4.0
        with:
          terraform-path: "${{ env.working-directory }}"
